console-reports:
  active: false

complexity:
  LargeClass:
    active: false
exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

style:
  UnusedImports:
    active: true